sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: Weng5835
  redis:
    host: localhost
    port: 6379
    password: 203000
    database: 10
  wechat:
    appid: wx8410663d9de3a83d
    secret: 331f938cb0863e9c583d0d940da09238